// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using konzolos_pizza_futar_vizsgaszeru;
//
//    var api = Api.FromJson(jsonString);

namespace konzolos_pizza_futar_vizsgaszeru
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Api
    {
        [JsonProperty("fazon")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Fazon { get; set; }

        [JsonProperty("fnev")]
        public string Fnev { get; set; }

        [JsonProperty("ftel")]
        public string Ftel { get; set; }
    }

    public partial class Api
    {
        public static Api[] FromJson(string json) => JsonConvert.DeserializeObject<Api[]>(json, konzolos_pizza_futar_vizsgaszeru.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Api[] self) => JsonConvert.SerializeObject(self, konzolos_pizza_futar_vizsgaszeru.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
